sudo: false
language: python
branches:
  only:
    - master
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/oc
python:
  - "3.6"
before_install:
  - pip install codecov
install:
  - pip install -r requirements/local.txt
before_script:
  - psql -U postgres -c 'CREATE DATABASE "oc";'
script:
  - coverage run manage.py test --settings=django_docker_example.settings
after_success:
  - codecov
notifications:
  email:
    on_success: always
    on_failure: always
