version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/production/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env
    volumes:
      - /app/static

  nginx:
    build: ./compose/production/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:5000"
    volumes_from:
      - django

  redis:
    image: redis:4.0.2